### ISSUE TITLE
Dockerfile or Containerfile

### ISSUE THREAD

**Issue by RaSerge** [aenix-io/talm#14]
Hello!
We are trying to adopt talm for air-gapped lab installation. Where is sources for image ghcr.io/aenix-io/cozystack/talos:v1.7.1. that used by Talm?

**Comment by kvaps** [comment]
Hi, sources are here:

https://github.com/aenix-io/cozystack/blob/dd1d9121f2cb6747aaafb0a9a795db03d339916f/packages/core/installer/images/talos/profiles/installer.yaml

You can build it using make from `packages/core/installer` directory:
```
make image-talos
```

**Comment by RaSerge** [comment]
Thank you!
