### ISSUE TITLE
Kubelet config in template

### ISSUE THREAD

**Issue by yenamax** [aenix-io/talm#19]
Hi,

This is more a question than an issue, sorry.

I just can't figure out how to configure "kubelet" as part of the template, I need to add extras mounts, how should I do it ?
Adding it directly to the "machine" dictionary doesn't work, as it's already defined before.

Thanks in advance.

**Comment by kvaps** [comment]
Hi, just edit your `templates/_helpers.tpl` and all the needed options into configuration.

**Comment by yenamax** [comment]
Thank you very much, it's working fine.
Nice product by the way !
