### ISSUE TITLE
Unnecessary error message using completion command

### ISSUE THREAD

**Issue by myasnikovdaniil** [aenix-io/talm#20]
### What is wrong?
Commands
```
talm completion ...
```
show error
```
Error loading configuration: error reading configuration file: open Chart.yaml: no such file or directory
```
completion scripts generation works, but shows annoying message if added to shell rc file.
### How it should work?
Talm shouldn't load configuration for commands that don't need any config file.

**Comment by kvaps** [comment]
Thank you for your replort, fixed in 441b7bf
