### ISSUE TITLE
"Warning: modeline parsing failed: modeline prefix not found"

### ISSUE THREAD

**Issue by TrooperT** [aenix-io/talm#22]
Attempting to separate device configurations into common template and then use fragments/patches to uniquify each machine.

Environment:
3 control plane nodes in same layer 2 segment: 10.32.158.0/24 
- cp01 @ .200
- cp02 @ .201
- cp03 @ .202

```shell
mkdir -p cluster/nodes && cd cluster
talm init
talm -e 10.32.158.200 -n 10.32.158.200 template -t templates/controlplane.yaml > nodes/cp200.yaml
mkdir patches
cat < EOF >> patches/patch.hostname-200.yaml
---
machine:
  network:
    hostname: controlplane-200

EOF
talm -e 10.32.158.200 -n 10.32.158.200 apply -i -f patches/patch.hostname-200.yaml -f nodes/cp200.yaml
```

This yields:
![Screen Shot 2024-09-11 at 11 57 31 AM](https://github.com/user-attachments/assets/5760b403-eea5-4c3c-9f13-2f80c2fd97e4)

Running the apply with file order reversed applies `nodes/cp200.yaml` but not `patches/patch.hostname-200.yaml`

![Screen Shot 2024-09-11 at 12 00 32 PM](https://github.com/user-attachments/assets/342bfbfe-7f3f-4ac0-9137-6db61cd5a764)

I feel like this is probably user error and seek guidance on how talm patch files should be formatted.

**Comment by kvaps** [comment]
Hi. The current flow does not allow to specify patches at the time of applying config, so you always have two phases:

1. Generate a separate configuration for every node, then apply configs to the nodes.
2. Another words you should do the at the phase of templating, eg:

```bash
cat < EOF >> templates/patch.hostname-200.yaml
---
machine:
  network:
    hostname: controlplane-200
EOF
``` 

then generate config for your node:
```
talm -e 10.32.158.200 -n 10.32.158.200 template -i -f templates/control-plane.yaml -f templates/patch.hostname-200.yaml > nodes/cp200.yaml
```

and apply it:
```
talm apply -f nodes/cp200.yaml
```

If you don't want to keep separate config for every node, you can use pipe:

```
talm template ... | talm apply -f-
```

**Comment by kvaps** [comment]
```
trying to manually add # talm: nodes=["10.32.158.200"], endpoints=["10.32.158.200"], templates=["templates/controlplane.yaml"] to my patch file... will report back
```

This is not going to work, because talm will consider it as node config and apply it twise

**Comment by TrooperT** [comment]
> ```
> trying to manually add # talm: nodes=["10.32.158.200"], endpoints=["10.32.158.200"], templates=["templates/controlplane.yaml"] to my patch file... will report back
> ```
> 
> This is not going to work, because talm will consider it as node config and apply it twise

Just say your 1st post and was reading through it. thanks for the quick reply. reading now :)

**Comment by kvaps** [comment]
BTW if you want to just specify hostname, you can manually edit your `nodes/cp200.yaml`, if you didn't change default template, it should be kept even after in-place upgade:

```
talm template -f nodes/cp200.yaml --in-place
```

**Comment by TrooperT** [comment]
ah I see. utilize the "patches" during the templating process to create the rendered node configurations. makes sense now... see it was user error :)
